packages:
  - "packages/*"
allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  msw: false
  workerd: true
overrides:
  "@types/react": "^19"
  "@types/react-dom": "^19"
  tsx: "4.23.10"
