// Authoring template for creating a .docx with docx-js (the `docx` npm package,
// pre-bundled in Kowork and resolvable via NODE_PATH). Copy this into a temp
// directory (never the user's folder), edit the copy's `children` array, and run
// it, writing the document to the path the user wants:
//
//     kowork-node create_docx.cjs out.docx
//
// It runs from a temp directory (never the user's folder); the copy is kept
// there after a successful write so you can edit it and re-run to revise the
// document in the same session (the OS reclaims temp later). Use the .cjs
// extension so `require` works even when the surrounding project is an ES module
// ("type": "module" in package.json).
//
// It demonstrates every "create" building block: heading levels, paragraphs, a
// bulleted list, a numbered list (needs a `numbering` config), a table, an
// inline image, a running header, a footer with page numbers, and an explicit
// US Letter page size (docx-js otherwise defaults to A4).
//
// Image note: docx-js needs explicit width/height in `transformation` (EMUs are
// derived for you from these pixel values); it does not auto-size. Read a real
// image's pixel size with Pillow (kowork-python -c "from PIL import Image;
// print(Image.open('photo.png').size)") and pass it. The tiny PNG below keeps
// this file self-contained; for a real image use fs.readFileSync("photo.png").

const fs = require("fs");
const path = require("path");
const {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  LevelFormat,
  Table,
  TableRow,
  TableCell,
  WidthType,
  ImageRun,
  Header,
  Footer,
  PageNumber,
} = require("docx");

const PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAFklEQVR42mNQTX5NEmIY1TCqYfhqAAB2SXMQ7LkbdQAAAABJRU5ErkJggg==";

const outPath = process.argv[2] || "output.docx";

const outExt = path.extname(outPath).toLowerCase();
if (outExt === ".docm" || outExt === ".dotm") {
  console.error(
    `error: refusing to write a macro-enabled document (${outExt}); macros are ` +
      "never authored here. Write a .docx instead.",
  );
  process.exit(1);
}

const doc = new Document({
  creator: "Kowork",
  title: "Kowork docx skill demo",
  numbering: {
    config: [
      {
        reference: "kowork-steps",
        levels: [
          {
            level: 0,
            format: LevelFormat.DECIMAL,
            text: "%1.",
            alignment: AlignmentType.START,
          },
        ],
      },
    ],
  },
  sections: [
    {
      // US Letter, 1" margins (DXA: 1440 = 1 inch). docx-js defaults to A4, so
      // set this explicitly; for A4 use { width: 11906, height: 16838 }.
      properties: {
        page: {
          size: { width: 12240, height: 15840 },
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
        },
      },
      headers: {
        default: new Header({
          children: [new Paragraph({ text: "Kowork — quarterly report" })],
        }),
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun("Page "),
                new TextRun({ children: [PageNumber.CURRENT] }),
                new TextRun(" of "),
                new TextRun({ children: [PageNumber.TOTAL_PAGES] }),
              ],
            }),
          ],
        }),
      },
      children: [
        new Paragraph({
          heading: HeadingLevel.TITLE,
          text: "Quarterly Report",
        }),

        new Paragraph({ heading: HeadingLevel.HEADING_1, text: "Overview" }),
        new Paragraph({
          children: [
            new TextRun("This document was generated by the Kowork "),
            new TextRun({ text: "docx skill", bold: true }),
            new TextRun(". Edit the children array to change it."),
          ],
        }),

        new Paragraph({ heading: HeadingLevel.HEADING_2, text: "Highlights" }),
        new Paragraph({ text: "First highlight", bullet: { level: 0 } }),
        new Paragraph({ text: "Second highlight", bullet: { level: 0 } }),

        new Paragraph({ heading: HeadingLevel.HEADING_2, text: "Next steps" }),
        new Paragraph({
          text: "Draft the plan",
          numbering: { reference: "kowork-steps", level: 0 },
        }),
        new Paragraph({
          text: "Review with the team",
          numbering: { reference: "kowork-steps", level: 0 },
        }),

        new Paragraph({ heading: HeadingLevel.HEADING_1, text: "Data" }),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              children: [
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [new TextRun({ text: "Metric", bold: true })],
                    }),
                  ],
                }),
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [new TextRun({ text: "Value", bold: true })],
                    }),
                  ],
                }),
              ],
            }),
            new TableRow({
              children: [
                new TableCell({ children: [new Paragraph("Revenue")] }),
                new TableCell({ children: [new Paragraph("$1.2M")] }),
              ],
            }),
          ],
        }),

        new Paragraph({ heading: HeadingLevel.HEADING_1, text: "Figure" }),
        new Paragraph({
          children: [
            new ImageRun({
              type: "png",
              data: Buffer.from(PNG_BASE64, "base64"),
              transformation: { width: 96, height: 96 },
            }),
          ],
        }),
      ],
    },
  ],
});

Packer.toBuffer(doc)
  .then((buffer) => {
    fs.writeFileSync(outPath, buffer);
    console.log("wrote", outPath, buffer.length, "bytes");
  })
  .catch((err) => {
    console.error("error:", err.message);
    process.exit(1);
  });
